baseURL = "https://codology.net/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "SICP Solutions"
enableRobotsTXT = true
enableEmoji = true
theme = "book"










googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

paginate = 20

[params]
	author = "Sébastien Gignoux"
	description = "Site Description"
	bio = "My solutions to the exercises of the book Structure and Interpretation of Computer Programs"

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = false
	enableToc = false

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = false
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = false
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = "ooops"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
# 	facebook-square = "https://www.facebook.com/nodejh"
# 	twitter-square = "https://www.twitter.com/nodejh"
 	github-square = "https://github.com/sgignoux"
 	linkedin-square = "https://www.linkedin.com/in/sebastiengignoux/"